# Generated by Django 4.2.2 on 2023-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('highest_sale_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_floor', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
