# Generated by Django 4.2.2 on 2023-06-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nftsales',
            table='nftsales',
        ),
    ]
