# Generated by Django 4.2.2 on 2023-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0002_alter_nftsales_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumTraders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buyers', models.IntegerField()),
                ('sellers', models.IntegerField()),
                ('unique_traders', models.IntegerField()),
            ],
            options={
                'db_table': 'ethereum_traders',
            },
        ),
    ]
