# Generated by Django 4.2.2 on 2023-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0003_ethereumtraders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCTraders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_buyers', models.IntegerField()),
                ('total_sellers', models.IntegerField()),
                ('total_traders', models.IntegerField()),
            ],
            options={
                'db_table': 'btc_traders',
            },
        ),
    ]
