# Generated by Django 4.2.2 on 2023-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0005_avgfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcUsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('users', models.IntegerField()),
            ],
            options={
                'db_table': 'btcusersdata',
            },
        ),
    ]
