# Generated by Django 4.2.2 on 2023-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0006_btcusersdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ethereum_addresses', models.IntegerField()),
                ('polygon_addresses', models.IntegerField()),
                ('arbitrum_addresses', models.IntegerField()),
                ('optimism_addresses', models.IntegerField()),
            ],
            options={
                'db_table': 'ethereumwallets',
            },
        ),
        migrations.CreateModel(
            name='GasFeesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ethereum_gas_usd', models.DecimalField(decimal_places=9, max_digits=10)),
                ('polygon_gas_usd', models.DecimalField(decimal_places=9, max_digits=10)),
                ('arbitrum_gas_usd', models.DecimalField(decimal_places=9, max_digits=10)),
                ('optimism_gas_usd', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
            options={
                'db_table': 'gasfeesdata',
            },
        ),
    ]
