# Generated by Django 4.2.2 on 2023-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0008_alter_gasfeesdata_arbitrum_gas_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftLowestSalePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('lowest_sale_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_floor', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'nft_lowest_sale_prices',
            },
        ),
    ]
