# Generated by Django 4.2.2 on 2023-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0010_nfttradesbychain_tradesbyplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('non_odrdinal_tx', models.IntegerField()),
                ('brc20_tx', models.IntegerField()),
                ('non_brc20_ordi_tx', models.IntegerField()),
                ('non_odrdinal_fee', models.DecimalField(decimal_places=8, max_digits=10)),
                ('brc20_fee', models.DecimalField(decimal_places=8, max_digits=10)),
                ('non_brc20_ordi_fee', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'db_table': 'bitcointransaction',
            },
        ),
        migrations.CreateModel(
            name='EthereumL2Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ethereum_transactions', models.IntegerField()),
                ('polygon_transactions', models.IntegerField()),
                ('arbitrum_transactions', models.IntegerField()),
                ('optimism_transactions', models.IntegerField()),
            ],
            options={
                'db_table': 'ethereum_l2_transactions',
            },
        ),
        migrations.CreateModel(
            name='VolumeByPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('platform', models.CharField(max_length=100)),
                ('volume', models.DecimalField(decimal_places=12, max_digits=18)),
            ],
            options={
                'db_table': 'volumebyplatform',
            },
        ),
    ]
