# Generated by Django 4.2.2 on 2023-07-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0011_bitcointransaction_ethereuml2transactions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinTransaction',
        ),
    ]
