# Generated by Django 4.2.2 on 2023-07-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0013_bitcointransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinTransaction',
        ),
    ]
