# Generated by Django 4.2.2 on 2023-07-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0014_delete_bitcointransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradesByPlatform',
        ),
    ]
