# Generated by Django 4.2.2 on 2023-07-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0015_delete_tradesbyplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('non_odrdinal_tx', models.IntegerField()),
                ('brc20_tx', models.IntegerField()),
                ('non_brc20_ordi_tx', models.IntegerField()),
                ('BRC20_Fee', models.DecimalField(decimal_places=8, max_digits=12)),
                ('non_BRC20_Ordi_Fee', models.DecimalField(decimal_places=8, max_digits=16)),
                ('non_Odrdinal_Fee', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'bitcointransaction',
            },
        ),
        migrations.AlterField(
            model_name='volumebyplatform',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
