# Generated by Django 4.2.2 on 2023-07-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0018_tradesbyplatform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcointransaction',
            old_name='non_odrdinal_Fee',
            new_name='non_odrdinal_fee',
        ),
    ]
