# Generated by Django 4.2.2 on 2023-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0019_rename_non_odrdinal_fee_bitcointransaction_non_odrdinal_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumNFTCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_sales', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lowest_sales', models.DecimalField(decimal_places=3, max_digits=10)),
                ('collection', models.CharField(max_length=100)),
                ('etherscan_link', models.URLField()),
                ('owners', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('blur_link', models.URLField()),
                ('gem_link', models.URLField()),
                ('uniswap_link', models.URLField()),
            ],
            options={
                'db_table': 'ethereum_nft_collections',
            },
        ),
    ]
