# Generated by Django 4.2.2 on 2023-07-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0020_ethereumnftcollections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinTransaction',
        ),
        migrations.DeleteModel(
            name='BtcUsersData',
        ),
        migrations.DeleteModel(
            name='EthereumL2Transactions',
        ),
        migrations.DeleteModel(
            name='EthereumWallets',
        ),
        migrations.DeleteModel(
            name='NftLowestSalePrices',
        ),
        migrations.DeleteModel(
            name='NFTSales',
        ),
        migrations.DeleteModel(
            name='NftTradesByChain',
        ),
    ]
