# Generated by Django 4.2.2 on 2023-07-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0023_ethereumtraders'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lowest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('collection', models.CharField(max_length=100)),
                ('etherscan_link', models.URLField()),
                ('owners', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('sellers', models.CharField(max_length=100)),
                ('blur_link', models.URLField()),
                ('gem_link', models.URLField()),
                ('uniswap_link', models.URLField()),
            ],
            options={
                'db_table': 'nft_stats',
            },
        ),
    ]
