# Generated by Django 4.2.2 on 2023-07-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0026_nftstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFTStats',
        ),
    ]
