# Generated by Django 4.2.2 on 2023-07-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0029_delete_nftstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lowest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyers', models.IntegerField()),
                ('collection', models.CharField(max_length=100)),
                ('owners', models.IntegerField()),
                ('sales_count', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('sellers', models.IntegerField()),
                ('blur_link', models.URLField()),
                ('gem_link', models.URLField()),
                ('uniswap_link', models.URLField()),
                ('wash_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('wash_volume_percentage', models.DecimalField(decimal_places=8, max_digits=20)),
                ('organic_volume', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'nft_stats',
            },
        ),
    ]
