# Generated by Django 4.2.2 on 2023-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0030_nftstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTStatsByPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyers', models.IntegerField()),
                ('project', models.CharField(max_length=100)),
                ('sales_count', models.IntegerField()),
                ('sellers', models.IntegerField()),
                ('wash_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('wash_volume_percentage', models.DecimalField(decimal_places=8, max_digits=20)),
                ('organic_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'nft_stats_by_platform',
            },
        ),
    ]
