# Generated by Django 4.2.2 on 2023-07-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0031_nftstatsbyplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyers', models.IntegerField()),
                ('organic_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sales', models.IntegerField()),
                ('sellers', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('wash_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('wash_volume_percentage', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'market_overview',
            },
        ),
    ]
