# Generated by Django 4.2.2 on 2023-07-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigaiDashboard', '0032_marketoverview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketOverview',
        ),
    ]
